static void draw_aimer (ttk_surface srf, int x, int y);
static void aimer_hold (ttk_surface srf, int x, int y);
static void aimer_shoot (ttk_surface srf, int x, int y);
static void startup_screen (ttk_surface srf);
static void duckhunt_score (ttk_surface srf);
static void dog_holdduck (ttk_surface srf);
static void dog_laughing (ttk_surface srf);
static void duck_flyaway (ttk_surface srf);
static void duck_shot (ttk_surface srf);
static void dog_walk (ttk_surface srf);
static void move_duck (ttk_surface srf);
static void reset_duckhunt();
static void move_duck();
static void init_duck();
static void hit_action();
static void move_up();
static void move_down();
static void move_left();
static void move_right();
